import express from 'express';
import { query, execute, getConnection } from '../config/db.js';
import { protectRoute } from '../middleware/auth.js';
import { emitToAll } from '../utils/socket.js';
import { sendMail } from '../utils/mailer.js';

const router = express.Router();
router.use(protectRoute);

router.post('/', async (req, res) => {
  const { gate_pass_number } = req.body;
  if (!gate_pass_number) return res.status(400).json({ message: 'Gate pass number is required' });

  let connection;
  try {
    const plans = await query(
      'SELECT * FROM despatch_plans WHERE status = "completed" AND gate_pass_number IS NULL'
    );

    if (plans.length === 0) {
      return res.status(400).json({ message: 'No completed parts to dispatch' });
    }

    const totalParts = plans.length;
    const totalQuantity = plans.reduce((sum, p) => sum + p.quantity, 0);
    const today = new Date().toISOString().split('T')[0];

    connection = await getConnection();
    await connection.beginTransaction();

    const [gpResult] = await connection.execute(
      'INSERT INTO gate_passes (user_id, gate_pass_number, plan_date, total_parts, total_quantity) VALUES (?, ?, ?, ?, ?)',
      [req.user.id, gate_pass_number, today, totalParts, totalQuantity]
    );
    const gpId = gpResult.insertId;

    for (const plan of plans) {
      await connection.execute(
        'INSERT INTO despatch_history (gate_pass_id, plan_id, part_number, quantity) VALUES (?, ?, ?, ?)',
        [gpId, plan.id, plan.part_number, plan.quantity]
      );
      
      await connection.execute(
        'UPDATE despatch_plans SET gate_pass_number = ?, dispatched_at = NOW(), updated_at = NOW() WHERE id = ?',
        [gate_pass_number, plan.id]
      );
    }

    await connection.commit();
    connection.release();

    emitToAll('despatch:gatepass', { gate_pass_number, user_id: req.user.id });

    // Send tabular email to users opted-in to receive despatch mails
    try {
      const emailUsers = await query(
        'SELECT email FROM users WHERE receive_despatch_mail = 1 AND is_active = 1 AND email IS NOT NULL AND TRIM(email) != ""'
      );
      const recipientEmails = emailUsers.map(u => u.email.trim()).filter(Boolean);

      if (recipientEmails.length > 0) {
        const rowsHtml = plans.map((p, idx) => `
          <tr style="border-bottom: 1px solid #e2e8f0;">
            <td style="padding: 10px 14px; text-align: center; color: #64748b; font-size: 13px;">${idx + 1}</td>
            <td style="padding: 10px 14px; font-weight: 600; color: #0f172a; font-family: monospace; font-size: 14px;">${p.part_number}</td>
            <td style="padding: 10px 14px; text-align: right; font-weight: 700; color: #0f172a; font-size: 14px;">${p.quantity}</td>
          </tr>
        `).join('');

        const emailHtml = `
          <div style="font-family: Arial, sans-serif; max-width: 650px; margin: 0 auto; background-color: #ffffff; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden;">
            <div style="background: linear-gradient(135deg, #0d9488 0%, #059669 100%); padding: 20px 24px; color: #ffffff;">
              <h1 style="margin: 0; font-size: 20px; font-weight: 700; letter-spacing: 0.5px;">RSB TRANSMISSIONS (I) LTD.</h1>
              <p style="margin: 4px 0 0 0; font-size: 14px; opacity: 0.9;">Vehicle Despatch Gate Pass Notification</p>
            </div>
            
            <div style="padding: 24px;">
              <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 16px; margin-bottom: 24px;">
                <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
                  <tr>
                    <td style="padding: 6px 0; color: #64748b; width: 40%;"><strong>Gate Pass Number:</strong></td>
                    <td style="padding: 6px 0; color: #0f172a; font-weight: 700; font-size: 15px;">#${gate_pass_number}</td>
                  </tr>
                  <tr>
                    <td style="padding: 6px 0; color: #64748b;"><strong>Plan Date:</strong></td>
                    <td style="padding: 6px 0; color: #0f172a;">${today}</td>
                  </tr>
                  <tr>
                    <td style="padding: 6px 0; color: #64748b;"><strong>Generated By:</strong></td>
                    <td style="padding: 6px 0; color: #0f172a;">${req.user.name || req.user.username} (@${req.user.username})</td>
                  </tr>
                  <tr>
                    <td style="padding: 6px 0; color: #64748b;"><strong>Total Parts / Total Qty:</strong></td>
                    <td style="padding: 6px 0; color: #0d9488; font-weight: 700;">${totalParts} parts &bull; ${totalQuantity} total qty</td>
                  </tr>
                </table>
              </div>

              <h3 style="font-size: 15px; color: #1e293b; margin: 0 0 12px 0; border-bottom: 2px solid #0d9488; padding-bottom: 6px;">
                Despatched Parts Details
              </h3>

              <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 13px;">
                <thead>
                  <tr style="background-color: #f1f5f9; color: #475569; font-size: 12px; text-transform: uppercase;">
                    <th style="padding: 10px 14px; text-align: center; border-bottom: 2px solid #cbd5e1; width: 60px;">SR No</th>
                    <th style="padding: 10px 14px; text-align: left; border-bottom: 2px solid #cbd5e1;">Part Number</th>
                    <th style="padding: 10px 14px; text-align: right; border-bottom: 2px solid #cbd5e1; width: 120px;">Quantity</th>
                  </tr>
                </thead>
                <tbody>
                  ${rowsHtml}
                  <tr style="background-color: #f8fafc; font-weight: 700;">
                    <td colspan="2" style="padding: 12px 14px; text-align: right; border-top: 2px solid #cbd5e1; color: #0f172a;">GRAND TOTAL:</td>
                    <td style="padding: 12px 14px; text-align: right; border-top: 2px solid #cbd5e1; color: #0d9488; font-size: 15px;">${totalQuantity}</td>
                  </tr>
                </tbody>
              </table>

              <p style="color: #94a3b8; font-size: 12px; margin: 24px 0 0 0; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 16px;">
                This is an automated notification sent by the RSB Despatch Management System.
              </p>
            </div>
          </div>
        `;

        sendMail({
          to: recipientEmails,
          subject: `Gate Pass Generated - #${gate_pass_number} - RSB Despatch`,
          html: emailHtml,
        }).catch(mailErr => {
          console.error('[GatePass] Error sending notification email:', mailErr?.message || mailErr);
        });
      }
    } catch (emailErr) {
      console.error('[GatePass] Error querying recipients for notification:', emailErr?.message || emailErr);
    }

    res.json({ message: 'Gate pass generated successfully', gate_pass_id: gpId });
  } catch (error) {
    if (connection) {
      try { await connection.rollback(); connection.release(); } catch(e) {}
    }
    console.error('Gate pass error:', error);
    res.status(500).json({ message: 'Server error generating gate pass' });
  }
});

router.get('/', async (req, res) => {
  try {
    const passes = await query('SELECT * FROM gate_passes ORDER BY created_at DESC LIMIT 100');
    
    for (let pass of passes) {
      const history = await query('SELECT * FROM despatch_history WHERE gate_pass_id = ?', [pass.id]);
      pass.history = history;
    }
    
    res.json(passes);
  } catch (error) {
    console.error('Error fetching gate passes:', error);
    res.status(500).json({ message: 'Server error' });
  }
});

export default router;
